<!-- _layouts/default.html -->

---
---

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page.title }}</title>
    <link rel="stylesheet" href="{{ "/assets/css/style.css" | relative_url }}">
</head>
<body>
    <header>
        <div class="container">
            <h1>{{ site.title }}</h1>
            <nav>
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="container">
        {{ content }}
    </div>

    <footer>
        <div class="container">
            <p>&copy; {{ site.title }} {{ site.time | date: "%Y" }}</p>
        </div>
    </footer>
</body>
</html>
